### ISSUE TITLE
Express Session

### ISSUE THREAD

**Issue by Ambrish5211** [rakshyak-98/bookish-buddies#10]
Error: secret option required for sessions
Jul 22 03:42:00 PM      at session (/opt/render/project/src/api/node_modules/express-session/index.js:200:12)
Jul 22 03:42:00 PM      at Layer.handle [as handle_request] (/opt/render/project/src/api/node_modules/express/lib/router/layer.js:95:5)
Jul 22 03:42:00 PM      at trim_prefix (/opt/render/project/src/api/node_modules/express/lib/router/index.js:328:13)
Jul 22 03:42:00 PM      at /opt/render/project/src/api/node_modules/express/lib/router/index.j

**Comment by yanicodeverse** [comment]
fixed environment variable key
